### ISSUE TITLE
Relying on aliases is bad

### ISSUE THREAD

**Issue by vabd** [Informo/specs#43]
Currently, the specs are telling every client implementation to build a list of entry nodes based on the set of `m.room.aliases` events in a room. This is bogus because:

* as already outlined [here](https://matrix.org/docs/spec/client_server/r0.4.0.html#m-room-aliases), this set isn't bound to reflect the reality of the list of aliases for a room.
* a malicious node could abuse room aliases, by setting an alias to a given room long enough so that it's widely stored in clients, then moving it to another room, which could broadcast propaganda or disinformation.
* there are ongoing discussions within the Matrix core team to get rid of `m.room.aliases` events given they're more painful to manage than actually useful.

One easy solution to work around this issue would be to impose to all client implementations to make sure all room aliases for a given room resolve to the given room.

A more complex but more efficient one would be to stop using room aliases altogether and only rely on room IDs, and build the list of entry nodes based on the list of servers in the room. We could also specify a state event that a node could send in order to indicate whether it wants to be an entry node, but this sounds a bit bogus as well since any user on the node could send that event. Another way of identifying entry nodes is by checking whether each node in the room allows guest registration, but that seems meh to me privacy-wise.

The first solution might be tricky and full of edge cases, and not future-proof, and we don't have a stable release of the specs yet so now is the good time to ditch everything with something completely new.

The only blurry point I can think of regarding the second solution is how to tell the difference between an entry node and a non-entry node. We could specify a state event that a node could send in order to indicate whether it wants to be an entry node, but this sounds a bit bogus since any user on the node could send that event. Another way of identifying entry nodes is by checking whether each node in the room has guest registration turned on, but that seems meh to me privacy-wise.

**Comment by vabd** [comment]
Writing down my thoughts some more here:

Option one is definitely off the table, because it's not future-proof.

When considering option two, the per-node state event would be the most viable option imho, as it makes no compromise on users' privacy, and a non willing node can protect itself from malicious users sending state events by disabling guest registration. That would cause false positives on client implementations (i.e. clients thinking a node is an entry one but hitting a close door), but I honestly think that's the best option (or rather the less bad one).

**Comment by GordonF42** [comment]
Another solution would be to treat every node on the federation as potential entrypoints, and let the client check if the node is useable when connecting to the entrypoint. This solution could lead to many unusable entrypoints, but this issue would probably be mitigated by TAs' ability to trust entrypoints.

This has the advantage of not having to deal with state events sent by unauthorized users. Howeverit also prevents the node from publishing any metadata related to its role in informo. Perhaps we could ask nodes to publish some informo-related data in the .well-known, but it would also make them easily identifiable by states as informo nodes.

**Comment by vabd** [comment]
> Another solution would be to treat every node on the federation as potential entrypoints, and let the client check if the node is useable when connecting to the entrypoint. This solution could lead to many unusable entrypoints, but this issue would probably be mitigated by TAs' ability to trust entrypoints.

Yes, this is the approach I'm going with, along with a .well-known file and taking into account how many users joined through this node.

> Perhaps we could ask nodes to publish some informo-related data in the .well-known, but it would also make them easily identifiable by states as informo nodes.

No more than aliases, imho.
