### ISSUE TITLE
Handle source/TA's homeserver blocking / shutting down

### ISSUE THREAD

**Issue by GordonF42** [Informo/specs#6]
What happens when a TA/source's original homeserver gets blocked or shuts down?
Obviously the user won't be able to edit its state events (TA / source data) nor send new messages (articles).
Can we provide a way for TA/source users move to a newer account on another homeserver ?

We can rely on the TA/source signing keys to attest its new identity, but it could also let an attacker having the private key overcome existing users (not necessarily bad, there's always some point of failure).
We can also ask the TA/source to host his own Matrix homeserver, but this is costly and require technical skills.

**Comment by vabd** [comment]
imho this would be done by having a TA originally trusting the entity blacklisting its previous account and trusting its new one.
I'll draft a SCS allowing a new source to say "hey, I was xxxx but couldn't keep my account for some reason" so client implementations can smoothly do the link between articles posted by a source's previous account and new ones. I think that's the best way to tackle this issue right now.
